### ISSUE TITLE
Error in ASR pre-training

### ISSUE THREAD

**Issue by sarapapi** [danliu2/caat#9]
Hi,
I am trying to reproduce your complete pipeline for your paper model and I started from the ASR pre-training, I used your code from the README. 
Unfortunately an error arises:
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq_cli/train.py", line 167, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq_cli/train.py", line 277, in train
    log_output = trainer.train_step(samples)
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/trainer.py", line 662, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/tasks/fairseq_task.py", line 475, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/criterions/label_smoothed_cross_entropy.py", line 82, in forward
    sample["target"].size(0) if self.sentence_avg else sample["ntokens"]
KeyError: 'ntokens'
```
I also looked at your [code here](https://github.com/danliu2/caat/blob/41d1099f01ce633e1dabb18455d03363ac151f48/rain/data/st_dataset.py#L110) and `ntokens` is not returned. Did I do something wrong?

**Comment by danliu2** [comment]
This is  a bug from last code merge. I've fixed it in commit e1cae5fcaae8531a47fb9c0cb387ffc4fa9005c4.  Sorry for the trouble caused by my negligence

**Comment by sarapapi** [comment]
Hi, the bug at training time is solved but not at validation time since you define `valid_step` twice. 
Thus, the error arises again when the validation step starts, here is the full stack:
```
2022-01-16 20:54:54 | INFO | fairseq_cli.train | begin validation on "valid" subset
Traceback (most recent call last):
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/train.py", line 16, in <module>
    cli_main()
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq_cli/train.py", line 489, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/distributed/utils.py", line 344, in call_main
    torch.multiprocessing.spawn(
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq_cli/train.py", line 167, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq_cli/train.py", line 291, in train
    valid_losses, should_stop = validate_and_save(
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq_cli/train.py", line 378, in validate_and_save
    valid_losses = validate(cfg, trainer, task, epoch_itr, valid_subsets)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq_cli/train.py", line 448, in validate
    trainer.valid_step(sample)
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/trainer.py", line 903, in valid_step
    _loss, sample_size, logging_output = self.task.valid_step(
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/../rain/tasks/s2s_task.py", line 297, in valid_step
    loss, sample_size, logging_output = super().valid_step(sample, model, criterion)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/tasks/fairseq_task.py", line 485, in valid_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/spapi/anaconda3/envs/caat_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/spapi/fairseq_simul/simul_CAAT/fairseq/fairseq/../fairseq/criterions/label_smoothed_cross_entropy.py", line 82, in forward
    sample["target"].size(0) if self.sentence_avg else sample["ntokens"]
KeyError: 'ntokens'
```

**Comment by danliu2** [comment]
Thanks, The duplicated valid_step processed on commit a7fd7a3
